#+title:      Hidriotáfia, Urna Mortuária
#+author: Sir Thomas Browne
#+subtitle: ou uma Dissertação acerca das Urnas Sepulcrais recém achadas em Norfolks

#+options: toc:nil num:nil
#+LANGUAGE: pt_BR


* A meu digno e honrado amigo Tomás Le Gros, de Crostwick, escudeiro

Extinta a pira funerária, e findo o valedicto, despediam os homens um demorado adeus a seus amigos enterrados, pouco esperando que a curiosidade das eras futuras lhes comentasse as cinzas, e não tendo nenhuma esperiência da duração de suas relíquias, caso algum faziam de tais considerações posteriores. 

Mas quem é que conhece a fortuna de seus ossos, ou quantas vezes é que morre e se enterra? Quem tem o oráculo de suas cinzas, ou de onde hão de ser elas espalhadas? Os restos de muitos jazem como as ruínas dos de Pompeu[fn:1], em todos os cantos da terra; e quando encontram vossas mãos, podem aparentar-vos ter vagado longe as que, numa viagem direta e meridiana[fn:2], possuem senão poucas milhas de terra conhecida entre vós e o Polo.

Que de novo deveram achar-se os ossos de Teseu em Atenas[fn:3], não era nada além de conjectura, e expectativa esperançosa; mas que deveram surgir convenientemente para servir-vos, era um dom dos céus e honra além de esperado.

Não podemos senão desejar que essas urnam tivessem o efeito de vasos teatrais, e de grandes urnas do hipódromo [fn:4] em Roma; porque ressoassem os aplausos e as honras que vos são devidas. Contudo tristes e sepulcrais são estes jarros, os quais vozes alegres não possuem, exprimindo silentemente a velha mortalidade, as ruínas de tempos esquecidos, que conseguem somente falar com vida por quanto tempo neste estado corruptível algumas partes podem estar incorruptas, até então capazes de durar mais do que os ossos ainda não nascidos, e do que o mais nobre pilar [fn:5] entre nós.

Não vo-las apresentamos de modo algum como visão estranha ou espetáculo desconhecido diante de vossos olhos, os quais hão testemunhado a melhor das urnas, e a mais nobre variedade de cinzas; que não sois vós próprio nenhum pequeno mestre de antiguidades, e podeis comandar os olhos de tantas faces imperiais; a qual vos ergue os pensamentos às coisas antigas, e à consideração de eras anteriores a vós, quando mesmo os viventes eram antiguidades; quando excedessem os vivos aos mortos, e partir-se deste mundo não significava propriamente juntar-se a um número maior [fn:6]. E assim conduzide vosso pensamento à antiguidade dos dias, o vero objeto do antiquário, a quem as mais antigas coisas lhe são jovens, e a própria terra é uma criança; e que sem o relato Egípcio [fn:7] dá pouca importância aos milhares.

Insinuou-nos a ocasião, não aproveitado ensejo de escrever sobre velharias, ou nos intrometer nos assuntos do antiquário. Pouco nos atraem os discursos sobre antiguidades, a quem temos ante nós escasso o tempo porque se compreendam novas coisas, ou que se nos decifrem as novas aprendidas . Mas em vê-las [as urnas] surgir tal qual jaziam, quase em silêncio diante de nós, ao menos em suma despercebidas, não desejamos que outra vez morressem, e que se enterrassem duas vezes entre nós.  

Demais, preservar os vivos, e reviver os mortos, manter os homens fora de suas urnas, e discursar sobre os fragmentos humanos que há nelas, não é impertinente a nossa profissão; cujo estudo é a vida e a morte, [nós] que diariamente testemunhamos a mortalidade, e que de todos os homens menos precisamos de /memento's/ artificiais, ou um caixão ao pé da cama, porque reflitamos sobre nossas covas.  

É tempo de observar os acontecimentos, e não deixar que nada de notável nos escape; a supinidade dos dias antigos trouxe o silêncio a tanta coisa, ou tanto martirizou o tempo de tal maneira as crônicas, que as mais engenhosas cabeças [fn:8] não encontram trabalhos fáceis porque se edifique uma nova Britânica. 

Oportuno é volver-nos aos tempos antigos, e contemplar nossos antepassados. Rareados os grandes exemplos, força é buscá-los no mundo passado. A singeleza foge, a iniquidade nos sobrevem a passos largos. Temos bastante que fazer porque se nos remontem o tempo presente e o tempo passado, e o todo o palco das coisas só nos serve à instrução. Uma peça completa de virtude deve compor-se a partir dos remendos de todas as eras, como todas as belezas da Grécia não puderam compor mais do que uma só formosa Vênus. 

Quando os ossos do rei Artur foram desenterrados, a velha raça talvez pensou ter testemunhado neles alguma origem de si mesma; [mas] dessas urnas ninguém pode pretender-se a parente, e pode apenas testemunhar as relíquias das pessoas que, em sua vida delas dando a lei a seus predecessores, após longo esquecimento, jazem agora à sua mercê. Mas rememorar a primitiva civilização que trarão a estas plagas, e nos esquecer dos idos há muito prejuízos, misericordiosamente preservamos seus ossos, e não mijamos sobre suas cinzas. 

No oferecimento dessas antiguidades não nos dirigimos às famílias antigas, que lhes têm subsistido ao tempo; estamos longe de erigir-vos o valor sobre os pilares de vossos antepassados, cujos méritos ilustrais. Honramos vossas velhas virtudes, conforme o tempo que vos antecede, as quais são o mais nobre dos brasões. E tendo longa experiência de vossa palavra afetuosa, vazia de ocos formalismos, plena de liberdade, contante e generosa honestidade, vos considero uma gema da antiga rocha [fn:10], e devo professar-me, mesmo às urnas e às cinzas.   

[fn:1] /Pompeios juvenes Asia atque Europa, sed ipsum terrá tegit Libyos/ [Os filhos de Pompeu estão cobertos pelas terras de Ásia e Europa; o próprio Pompeu, pelas de África].

[fn:2] Não tão direta que não seja o mar entre vossa casa e a Groelândia. 

[fn:3] Trazidas por Címon. Plutarco. 

[fn:4] As grandes urnas no hipódromo em Roma concebidas para ressoar a voz das gentes em seus espetáculos. 

[fn:5] A que dignamente possui aquele vero gentil-homem Sir Horatio Townshend, meu honrado amigo.

[fn:6] /Abiit ad plures./

[fn:7] O qual faz o mundo contar muitos anos.

[fn:8] Em que o senhor Dugdale muito bem se esforçara, e digno de respeito pelas gentes sabidas e nobres; 
